import numpy as np
list = [3,34,23,4245,521,51]
print(list)
print(type(list))
barray = np.array(list)
print(barray)
print(type(barray))
aarray = np.array([[3, 12], [4, 34], [23,322]])
print(aarray)
print(type(aarray))
print(barray.ndim)
print(aarray.ndim)
print(barray.shape)
print(aarray.shape)
print(barray.size)
print(aarray.size)
ds = np.arange(1, 101)
sd = ds * 2
print(sd)
print(ds)
dsk = np.arange(2, 99, 2)
print(dsk)
bnd = np.arange(5, 105, 5)
print(bnd)
ghj = np.arange(1, 100)
print(ghj)
fdska = np.random.permutation(ghj)
print(fdska)
dkfsa = np.random.randint(1, 10, (3, 2))
print(dkfsa)
nk = np.random.rand(2, 3)
print(nk)
e = np.random.uniform(5, 1000, (3, 2))
print(e)
df = ["mike", "sean", "mark", "shane", "insym"]
name = np.random.choice(df, (5, 2))
print(name)
dfa = ghj.reshape(9, 11)
print(dfa)
fd = np.sort(fdska)
print(fd)
z1 = np.zeros((209275, 28934))
print(z1)
da = np.ones((230493, 12346))
print(da)
dfs = np.linspace(10000, 129939, 2432)
print(dfs)
for num in list:
    print(num * 2)